#config_version=5

# Lamp Matrix
# Need to change the names to match the current matrix names
lights:
  l_shoot_again:
    number: 2-0-0
    subtype: matrix
    tags: col1, row1
  l_left_special:
    number: 2-0-1
    subtype: matrix
    tags: col1, row2
  l_right_special:
    number: 2-0-2
    subtype: matrix
    tags: col1, row3
  l_2x:
    number: 2-0-3
    subtype: matrix
    tags: col1, row4
  l_3x:
    number: 2-0-4
    subtype: matrix
    tags: col1, row5
  l_star_1:
    number: 2-0-5
    subtype: matrix
    tags: col1, row6
  l_star_2:
    number: 2-0-6
    subtype: matrix
    tags: col1, row7
  l_1000_bonus:
    number: 2-0-7
    subtype: matrix
    tags: col1, row8
  l_2000_bonus:
    number: 2-0-8
    subtype: matrix
    tags: col2, row1
  l_3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus3000_bonus:
    number: 2-0-9
    subtype: matrix
    tags: col2, row2
  l_4000_bonus:
    number: 2-0-10
    subtype: matrix
    tags: col2, row3
  l_5000_bonus:
    number: 2-0-11
    subtype: matrix
    tags: col2, row4
  l_6000_bonus:
    number: 2-0-12
    subtype: matrix
    tags: col2, row5
  l_7000_bonus:
    number: 2-0-13
    subtype: matrix
    tags: col2, row6
  l_8000_bonus:
    number: 2-0-14
    subtype: matrix
    tags: col2, row7
  l_9000_bonus:
    number: 2-0-15
    subtype: matrix
    tags: col2, row8
  l_10000_bonus:
    number: 2-0-17
    subtype: matrix
    tags: col3, row2
  l_20000_bonus:
    number: 2-0-18
    subtype: matrix
    tags: col3, row3
  l_A:
    number: 2-0-19
    subtype: matrix
    tags: col3, row4
  l_B:
    number: 2-0-20
    subtype: matrix
    tags: col3, row5
  l_C:
    number: 2-0-21
    subtype: matrix
    tags: col3, row6
  l_D:
    number: 2-0-22
    subtype: matrix
    tags: col3, row7
  l_E:
    number: 2-0-23
    subtype: matrix
    tags: col3, row8
  l_1_target:
    number: 2-0-24
    subtype: matrix
    tags: col4, row1
  l_2_target:
    number: 2-0-25
    subtype: matrix
    tags: col4, row2
  l_3_target:
    number: 2-0-26
    subtype: matrix
    tags: col4, row3
  l_4_target:
    number: 2-0-27
    subtype: matrix
    tags: col4, row4
  l_1_target_arrow:
    number: 2-0-28
    subtype: matrix
    tags: col4, row5
  l_2_target_arrow:
    number: 2-0-29
    subtype: matrix
    tags: col4, row6
  l_3_target_arrow:
    number: 2-0-30
    subtype: matrix
    tags: col4, row7
  l_4_target_arrow:
    number: 2-0-31
    subtype: matrix
    tags: col4, row8
  l_magnet_5000:
    number: 2-0-32
    subtype: matrix
    tags: col5, row1
  l_magnet_10000:
    number: 2-0-33
    subtype: matrix
    tags: col5, row2
  l_magnet_20000:
    number: 2-0-34
    subtype: matrix
    tags: col5, row3
  l_magnet_30000:
    number: 2-0-35
    subtype: matrix
    tags: col5, row4
  l_magnet_50000:
    number: 2-0-36
    subtype: matrix
    tags: col5, row5
  l_top_jet_bumper:
    number: 2-0-37
    subtype: matrix
    tags: col5, row6
  l_left_jet_bumper:
    number: 2-0-38
    subtype: matrix
    tags: col5, row7
  l_bottom_jet_bumper:
    number: 2-0-39
    subtype: matrix
    tags: col5, row8
  l_GAR_5000:
    number: 2-0-40
    subtype: matrix
    tags: col6, row1
  l_GOR:
    number: 2-0-41
    subtype: matrix
    tags: col6, row2
  l_GAR:
    number: 2-0-42
    subtype: matrix
    tags: col6, row3
  l_eject_hole_10000:
    number: 2-0-43
    subtype: matrix
    tags: col6, row4
  l_eject_hole_15000:
    number: 2-0-44
    subtype: matrix
    tags: col6, row5
  l_eject_hole_extra_ball:
    number: 2-0-45
    subtype: matrix
    tags: col6, row6
  l_spinner_1000:
    number: 2-0-46
    number: 2-0-47
    subtype: matrix
    tags: col6, row8
  l_1_can_play:
    number: 2-0-49
    subtype: matrix
    tags: col7, row2
  l_2_can_play:
    number: 2-0-50
    subtype: matrix
    tags: col7, row3
  l_3_can_play:
    number: 2-0-51
    subtype: matrix
    tags: col7, row4
  l_4_can_play:
    number: 2-0-52
    subtype: matrix
    tags: col7, row5
  l_match:
    number: 2-0-53
    subtype: matrix
    tags: col7, row6
  l_ball_in_play:
    number: 2-0-54
    subtype: matrix
    tags: col7, row7
  l_credits:
    number: 2-0-55
    subtype: matrix
    tags: col7, row8
  l_1_player_up:
    number: 2-0-56
    subtype: matrix
    tags: col8, row1
  l_2_player_up:
    number: 2-0-57
    subtype: matrix
    tags: col8, row2
  l_3_player_up:
    number: 2-0-58
    subtype: matrix
    tags: col8, row3
  l_4_player_up:
    number: 2-0-59
    subtype: matrix
    tags: col8, row4
  l_tilt:
    number: 2-0-60
    subtype: matrix
    tags: col8, row5
  l_game_over:
    number: 2-0-61
    subtype: matrix
    tags: col8, row6
  l_same_player_shoots:
    number: 2-0-62
    subtype: matrix
    tags: col8, row7
  l_high_score_to_date:
    number: 2-0-63
    subtype: matrix
    tags: col8, row8

